### PR TITLE
Background operations

### PR DESCRIPTION
**Pull request by SoftAdviceJR**
So after about 5 minutes I gave up on custom property dispatchers because it
1. Seemed kinda unnecessary
2. Seemed impossible

So I moved on with my mega-beast of joining VAFs and the next thing that I encountered were background tasks.
I've implemented something that seems to work (though I haven't thoroughly tested yet). 

I'll test some more tomorrow, but wanted to share the ideas I've had.

### CODE REVIEW

**Comment by SoftAdviceJR** [comment]
Screenshot 2021-02-18 091128
Screenshot 2021-02-18 091210
Screenshot 2021-02-18 091306

Both the recurring and on demand background operation seem to work and the on demand background operation seems to take it's parameters correctly.

**Comment by SoftAdviceJR** [comment]
The next thing I'm going to need is licensing on this first module.
I'm thinking it would be nice to have a
[LicenseRequired(Modules = new string[] {"Module 1"})]
attribute above classes that should only be loaded when a license is required.

I'm thinking I'd like to try using the decorator pattern on the dispatchers for this.
I might have to rework the Commands bit a little for that to work, is that ok?

By the way I'm just naming things as I go along, so if you want a different naming schema, please say so 😄

**Comment by FredTheDane** [comment]
@SoftAdviceJR Great work, albeit, not really tested in the test project or anything haha.
I am able to look past it, as it is an annoying thing to test...

And also good idea about Licensing requirements set as attributes, and yeah feel free to rework the Commands a little to get it to work. I have already put some effort into making the dispatchers a little more performant with the introduction of a type cache and additional assemblies. Those methods are in the IDispatcher interface.

**Comment by FredTheDane** [comment]
Actually, fantastic work on the background operations @SoftAdviceJR 🚀

**Pull request merged**
